# Generated by Django 5.2.13 on 2026-04-30 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('saved_filename', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('file_size', models.PositiveBigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('WARNING', 'Warning'), ('BLOCKED', 'Blocked')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
